name: 中青Python版本

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 5-23 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip3 install requests
    - name: Run Script
      env:
        YOUTH_HEADER1: ${{ secrets.YOUTH_HEADER1 }}
        YOUTH_READBODY1: ${{ secrets.YOUTH_READBODY1 }}
        YOUTH_REDBODY1: ${{ secrets.YOUTH_REDBODY1 }}
        YOUTH_READTIMEBODY1: ${{ secrets.YOUTH_READTIMEBODY1 }}
        YOUTH_WITHDRAWBODY1: ''
        DD_BOT_ACCESS_TOKEN: ${{ secrets.DD_BOT_ACCESS_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      run: |
        python youth.py